---
title: "5_phylopathAnalysis"
output: html_document
---

## Purpose

To test data consistency and get phylogenetic path coefficients using the 'phylopath' package.

Phylopath tests d-separation while accounting for phylogeny.

### Step 1: Load libraries

Load the libraries used.

```{r}
# Load tidyverse for sanity
library(tidyverse)

# Load ape for phylogenetic tree manipulation
library(ape)

# Load phylopath for analysis
library(phylopath)

# Load libraries for combining plots
library(cowplot)
library(gridExtra)
library(grid)
```

### Step 2: Load data and create models to compare

```{r}
# Load shark data and update categorical variables
sharkData <- read.csv("Data/SharkData/TraitData.csv") %>%
  # See 1_Supplemental_CategoricalAnalysis for Benthopelagic > Benthic and Deepwater > Coastal
  # Benthopelagic > Benthic
  mutate(WaterColumnPosition = case_when(
   str_detect(WaterColumnPosition, "Pelagic") ~ "Pelagic",
   WaterColumnPosition == "Benthic" ~ "Benthic",
   WaterColumnPosition == "Benthopelagic" ~ "Benthic")) %>%
  # Deepwater > Coastal
  mutate(PrimaryHabitat = case_when(
   str_detect(PrimaryHabitat, "Pelagic") ~ "Oceanic",
   PrimaryHabitat == "Deepwater" ~ "Coastal",
   PrimaryHabitat == "Coastal" ~ "Coastal"))
```

Create model structure.

```{r}
# Rename columns for displaying with phylopath
sharkDataAbrv <- sharkData %>% 
  rename(GillHeight = ProportionalGillAverage,
         MaxBodySize = MaximumBodySize,
         AvgTemp = AvgTemperature,
         WaterColumn = WaterColumnPosition,
         HabitatUse = PrimaryHabitat)

# Convert WaterColumn and HabitatUse to a factor
sharkDataAbrv$WaterColumn <- as.factor(sharkDataAbrv$WaterColumn)
sharkDataAbrv$HabitatUse <- as.factor(sharkDataAbrv$HabitatUse)

# Log Maximum Body Size
sharkDataAbrv$MaxBodySize = log(sharkDataAbrv$MaxBodySize)

# Set variables to be scaled
vars_to_scale <- c("MaxBodySize", "GillHeight", "AvgTemp")

# Center and scale continuous variables
sharkDataScaled <- sharkDataAbrv %>%
  mutate(across(all_of(vars_to_scale), scale)) %>%
  # Log CFAR due to Gamma log-linked distribution
  mutate(CFAR = log(CFAR))

# Define model set
models <- define_model_set(
  DispersalPotential  = c(GillHeight ~ WaterColumn),
  # Relationships all models have in common
  .common = c(MaxBodySize ~ AvgTemp,
              MaxBodySize ~ WaterColumn,
              GillHeight ~ MaxBodySize,
              CFAR ~ WaterColumn,
              CFAR ~ GillHeight,
              CFAR ~ MaxBodySize)
  )

# Create data frame for label positions
positions <- data.frame(
  name = c('AvgTemp',  'WaterColumn',
           'MaxBodySize', 'GillHeight', 
           'CFAR'),
  x = c(1.7, 1.3, 
        2.1, 1.4,
        2),
  y = c(4, 2.3, 
        3.5, 1.5,
        1)
)

plot_model_set(models, manual_layout = positions, edge_width = 0.75,
               box_x = 30, box_y = 7, curvature = 0.1)
```


### Step 4: Load tree data

```{r}
# Read in all 500 trees
FullTree <- read.nexus("Data/SharkData/PhyloTrees.nex")

# Set the seed
set.seed(125)

# Sample out a single tree
SampleFullTree <- sample(FullTree, 1)[[1]]

# Check if tips are binary
is.binary(SampleFullTree)

# Check tip labels
SampleFullTree$tip.label

# Check length of df = length of tree (should print TRUE)
length(sharkData$Genus_species) == length(SampleFullTree$tip.label)

# Set species names as row names
rownames(sharkDataScaled) <- sharkDataScaled$Genus_species
```

### Step 5: Evaluate the d-separation implications of DAG

```{r}
# Run phylo_path on the model sets
result <- phylo_path(models, data = sharkDataScaled, 
                     tree = SampleFullTree, model = "lambda", 
                     method = "logistic_MPLE")

# View the results
result

# Summary of results
s <- summary(result)

# View the summary
s

write.csv(s, "Results/Tables/phylopathModel.csv", row.names = FALSE)

# Plot the relative importance of all four models
importancePlot <- plot(s)

# View plot
importancePlot

# Turn s into a dataframe to plot importance nicely
modelWeights <- data.frame(s)
# Terrible coding practice, but the model is technically within 2 CICc, because there's nothing to compare to
modelWeights$LegendGroup <- "Within 2 CICc"

# Basically recreate the default plot, but pretty
modelsPlot <- ggplot(modelWeights, 
                        aes(x = reorder(model, p), y = p,
                            fill = LegendGroup)) +
  geom_col(color = 'black') +
  geom_text(aes(label = round(p, 3)),
            hjust = 1.1,                
            size = 4,
            color = "white") +
  coord_flip() +
  scale_fill_manual(values = '#c97373', name = NULL) +
  labs(x = NULL, y = NULL) +
  theme_classic() +
  theme(axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    legend.text = element_text(size = 12),
    legend.position = "inside",
    legend.position.inside = c(0.85, 0.05))

modelsPlot

# Extract the best model
best_model <- best(result)

best_positions <- data.frame(
  name = c('AvgTemp',
           'MaxBodySize',
           'WaterColumn',
           'GillHeight', 
           'CFAR'),
  x = c(10, 
        10, 
        3, 
        17.5,
        13.3),
  y = c(7.8, 
        5.5, 
        2.9, 
        3.8,
        1))

# Plot the best model
bestModelPlot <- plot(best_model, manual_layout = best_positions,
                  edge_width = 0.75, text_size = 7,
                  box_x = 27, box_y = 8, curvature = 0.05) +
                  ggplot2::xlim(0, 20) +
                  ggplot2::theme(legend.position = "inside",
                                 legend.position.inside = c(0.9, 0.85))

bestModelPlot <- plot(best_model, manual_layout = best_positions,
                  edge_width = 0.6, text_size = 3,
                  box_x = 15, box_y = 5, curvature = 0.05) +
                  ggplot2::xlim(0, 20) +
                  ggplot2::theme(legend.position = "none",
                                 text = element_text(size = 7)) +
                  ggplot2::annotate("text", x = 12.1, y = 6.5,
                                    label = "Negative",
                                    color = "firebrick", size = 2.5) +
                  ggplot2::annotate("text", x = 17.1, y = 4.55,
                                    label = "Positive",
                                    color = "navy", size = 2.5) +
                  ggplot2::annotate("text", x = 10, y = 0.5,
                                    label = "CICc:29.97, p-value: 0.51",
                                    color = "black", size = 3)

bestModelPlot
```

```{r}
# Create the coefficient plot
bestModelTable <- as.data.frame(best_model$coef)

pathLabels <- c(
  "GillHeight -> CFAR",
  "MaxBodySize -> CFAR",
  "MaxBodySize -> GillHeight",
  "WaterColumn -> CFAR",
  "WaterColumn -> GillHeight",
  "WaterColumn -> MaxBodySize",
  "AvgTemp -> MaxBodySize"
)

# Plot coefficients
coef_plot(best_model, error_bar = "se", 
          order_by = "strength") +
  ggplot2::coord_flip() +
  ggplot2::theme_classic() +
  ggplot2::labs(y = "Standardized Path Coefficient") +
  ggplot2::scale_x_discrete(labels = pathLabels)

# Set custom colors based on coefficients
coef_colors <- c("firebrick",
                 "navy",
                 "navy",
                 "navy",
                 "navy",
                 "navy",
                 "navy")


coeffPlot <- coef_plot(best_model, error_bar = "se", 
                              order_by = "strength") +
  ggplot2::coord_flip() + 
	ggplot2::theme_classic() +
	ggplot2::geom_errorbar(size = 0.5, color = "black", width = 0) +
	ggplot2::geom_point(size = 3, color = coef_colors) +
  ggplot2::labs(y = "Standardized Path Coefficient") +
  ggplot2::theme(axis.title = element_text(size = 7),
                 axis.text = element_text(size = 5))

coeffPlot
```

```{r}
# Combine plots and save
Figure5 <- plot_grid(
  bestModelPlot, coeffPlot,
  ncol = 2,
  rel_widths = c(0.9, 1.1),
  labels = c("a", "b"),
  label_size = 8
)

Figure5

# Save best model plot as a png
ggsave("Results/Figures/Fig5.tiff",
       plot = Figure5, units = "px",
       device = "tiff",
       width = 2160, height = 1450,
       dpi = 300)
```

