---
title: "X_phylogeneticAnalysis"
output: html_document
---

## Purpose

To resolve taxonomic differences between different data files and VertLife trees.

### Step 1: Load libraries

Load the libraries used.

```{r}
# Load tidyverse for sanity
library(tidyverse)

# Load phytools, ape, and geiger for working with phylogenetic trees
library(phytools)
library(ape)
library(geiger)

# Load ggtree and ggtreeExtrafor plotting phylogenetic tree
library(ggtree)
library(ggtreeExtra)

# Load scico 
library(scico)
```

### Step 2: Load files

Load:
* Nexus file (PhyloTrees.nex) 
* Shark trait data (TraitData.csv)

```{r}
# Read the tree file
Trees <- read.nexus("Data/SharkData/PhyloTrees.nex")

# Use read.csv to load shark trait data
sharkData <- read.csv("Data/SharkData/TraitData.csv")
```

### Step 3: Sample a tree and make sure they match

```{r}
# Set seed for reproducability
set.seed(123)

# Sample a single tree from Trees
sharkTree <- sample(Trees, 1)[[1]]

# Set row names as species names
rownames(sharkData) <- sharkData$Genus_species

# Check species with setdiff (should return "character (0)")
setdiff(sharkTree$tip.label, sharkData$Genus_species)
```

### Step 4: Get some higher level taxonomic information

```{r}
# Create a data frame of just the data we want
sharkTraits <- sharkData %>%
  select(Genus_species, Order, CFAR)
```

```{r}
# Create a named list of species per Order
order_groups <- split(sharkTraits$Genus_species, sharkTraits$Order)

# Get MRCA nodes
order_nodes <- sapply(order_groups, function(x) getMRCA(sharkTree, x))
order_nodes

# Create colors for each Order
order_colors <- scico(n = length(order_nodes), palette = "batlow")
names(order_colors) <- names(order_nodes)
```

### Step 5: Plot phylogenetic tree

```{r}
# Plot the tree before we go wild
phyloTree <- ggtree(sharkTree)

# Look at tree
phyloTree
```

```{r}
# Get plotted data
tree_data <- phyloTree$data

# Compute y positions for all Orders
order_y <- sapply(names(order_nodes), function(o) {
  node_number <- order_nodes[o]
  tree_data$y[tree_data$node == node_number]
})

# Print node positions
order_y
```

```{r}
# Add colors to Orders
phyloTreeOrder <- ggtree(sharkTree, linewidth = 0.3)

for (o in names(order_nodes)) {
  phyloTreeOrder <- phyloTreeOrder +
    geom_hilight(node = order_nodes[o], fill = order_colors[o], alpha = 0.2)
}

# Add CFAR bars
phyloTreePlot <- phyloTreeOrder +
  geom_fruit(
    data = sharkTraits,
    geom = geom_bar,
    mapping = aes(y = Genus_species, x = CFAR, fill = CFAR),
    orientation = "y",
    stat = "identity",
    pwidth = 0.2
  ) +
  scale_fill_scico(palette = "cork") +
  annotate("text", x = 0.59, y = 447, label = "Carcharhiniformes", size = 2.5) +
  annotate("text", x = 0.55, y = 6, label = "Echinorhiniformes", size = 2.5) +
  annotate("text", x = 0.81, y = 133, label = "Heterodontiformes", size = 2.5) +
  annotate("text", x = 0.57, y = 2, label = "Hexanchiformes", size = 2.5) +
  annotate("text", x = 0.82, y = 187, label = "Lamniformes", size = 2.5) +
  annotate("text", x = 0.77, y = 175, label = "Orectolobiformes", size = 2.5) +
  annotate("text", x = 0.55, y = 15, label = "Pristiophoriformes", size = 2.5) +
  annotate("text", x = 0.86, y = 124, label = "Squaliformes", size = 2.5) +
  theme(legend.position = "inside",
        legend.position.inside = c(0.96, 0.07),
        legend.key.size = unit(0.45, "cm"),
        legend.background = element_rect(fill = "transparent"),
        legend.title.position = "top",
        legend.title = element_text(hjust = 0.5))

phyloTreePlot

ggsave("Results/Figures/FigX.png", phyloTreePlot, units = "px",
       width = 1062, height = 2350, dpi = 300)
```
